TestUngDung/Areas/Admin/Controllers/DetailProductController.cs
using ModelEF.Dao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestUngDung.Areas.Admin.Controllers
{
    public class DetailProductController : Controller
    {
        // GET: Admin/DetailProduct
        public ActionResult Index(System.Int32 id)
        {
            var product_detail = new DetailProductDao();
            var model = product_detail.ListWhereAll(id);
            return View(model);
        }
    }
}

TestUngDung/Areas/Admin/Controllers/ProductController.cs
using ModelEF.Dao;
using ModelEF.EF;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestUngDung.Areas.Admin.Controllers
{
    public class ProductController : BaseController
    {
        // GET: Admin/Product
        TangThiDiemHuongContext db = new TangThiDiemHuongContext();
        public ActionResult Index(string searchString)
        {
            var product = new ProductDao();
            var model = product.ListWhereAll(searchString);
            ViewBag.searchString = searchString;
            return View(model);
        }
        [HttpGet]
        public ActionResult Create()
        {
            setViewBag();
            return View();
        }
        public void setViewBag(int? selectedID = null)
        {
            var dao = new CategoryDao();
            ViewBag.IDCategory = new SelectList(dao.ListAll(), "ID", "Name", selectedID);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product sp, HttpPostedFileBase Image)
        {


            if (Image != null && Image.ContentLength > 0)
            {
               
                string _FileName = Path.GetFileName(Image.FileName);
                string _path = Path.Combine(Server.MapPath("~/Upload/sanpham/" + _FileName));
                Image.SaveAs(_path);

                sp.Image = _FileName;

            }

            if (ModelState.IsValid)
            {
                db.Product.Add(sp);
                db.SaveChanges();
                SetAlert("Thêm Sản Phẩm Thành Công", "success");
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public ActionResult Edit(System.Int32 id)
        {
            var product = new ProductDao();
            var result = product.FindId(id);
            setViewBag(result.ID);
            if (result != null)
                return View(result);
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product sp, HttpPostedFileBase Image)
        {
            Product unv = db.Product.FirstOrDefault(x => x.ID == sp.ID);

            if (unv != null)
            {
                unv.IDCategory = sp.IDCategory;
                unv.Name = sp.Name;
                unv.UnitCost = sp.UnitCost;
                unv.Quantity = sp.Quantity;
                unv.Description = sp.Description;
                unv.Status = sp.Status;
                if (Image != null && Image.ContentLength > 0)
                {
                    int id = sp.ID;

                    string _FileName = "";
                    _FileName = Path.GetFileName(Image.FileName);
                    string _path = Path.Combine(Server.MapPath("~/Upload/sanpham/" + _FileName));
                    Image.SaveAs(_path);
                    unv.Image = _FileName;
                }
            }

            if (ModelState.IsValid)
            {
                db.SaveChanges();
                SetAlert("Cập Nhật Sản Phẩm Thành Công", "success");
                return RedirectToAction("Index");
            }
            setViewBag(sp.ID);
            return View();
        }
        public JsonResult Delete(System.Int32 id)
        {

            var product = new ProductDao();
            bool re = product.Delete(id);
            return Json(re, JsonRequestBehavior.AllowGet);
        }
    }
}

TestUngDung/Areas/Client/Controllers/ProductsController.cs
using ModelEF.Dao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestUngDung.Areas.Client.Controllers
{
    public class ProductsController : Controller
    {
        // GET: Client/Products
        public ActionResult Index()
        {
            var product = new ProductDao();
            var model = product.ListAll();
            return View(model);
        }
    }
}

TestUngDung/Areas/Admin/Views/Product/Create.cshtml
@model ModelEF.EF.Product

@{
    ViewBag.Title = "Thêm Sản Phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{
    <h5>Thêm Sản Phẩm</h5>
}

@using (Html.BeginForm("Create", "Product", FormMethod.Post,
    new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="col-lg-12 form-group">
            <div class="col-md-6">
                @Html.ActionLink("Quay Lại", "Index", "Product", new { @class = "btn btn-info" })
            </div>
        </div>
        <div class="col-lg-12 form-group">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UnitCost, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.UnitCost, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UnitCost, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Quantity, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="col-md-10">
                        <input type="file" name="Image" id="Image" class="form-control" accept="image/*" />
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Status, new List<SelectListItem>
                        {
                            new SelectListItem {Text = "Hiển Thị", Value = "1"},
                            new SelectListItem {Text = "Ẩn", Value = "0"}
                        }, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IDCategory, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.IDCategory, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IDCategory, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Thêm" class="btn btn-info" />
                </div>
            </div>
        </div>
    </div>
}

TestUngDung/Areas/Admin/Views/Product/Edit.cshtml
@model ModelEF.EF.Product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{
    <h5>Cập Nhật Sản Phẩm</h5>
}

@using (Html.BeginForm("Edit", "Product", FormMethod.Post,
    new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="col-lg-12 form-group pt-3">
            <div class="col-md-6">
                @Html.ActionLink("Quay Lại", "Index", "Product", new { @class = "btn btn-info" })
            </div>
        </div>
        <div class="col-lg-12 form-group">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UnitCost, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.UnitCost, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UnitCost, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Quantity, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="col-md-10">
                        <input type="file" name="Image" id="Image" class="form-control" accept="image/*" />
                        <img style="width:50px;height:50px" src="~/Upload/sanpham/@Model.Image" />
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Description, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Status, new List<SelectListItem>
                         {
                             new SelectListItem {Text = "Hiển Thị", Value = "1"},
                             new SelectListItem {Text = "Ẩn", Value = "0"}
                         }, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IDCategory, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.IDCategory, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IDCategory, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lưu" class="btn btn-info" />
                </div>
            </div>
        </div>
    </div>
}

TestUngDung/Areas/Admin/Views/Product/Index.cshtml
@model List<ModelEF.ViewModel.ProductModel>


@{
    ViewBag.Title = "Quản Lý Sản Phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{
    <h4>Quản Lý Sản Phẩm</h4>
}
@using (Html.BeginForm("Index", "Product", FormMethod.Post))
{
    <div class="col-lg-12 form-group">
        <div class="col-md-6">
            @Html.ActionLink("+ Tạo mới", "Create", "Product", new { @class = "btn btn-info" })
        </div>
        <div class="col-md-4">
            <input type="text" value="@ViewBag.searchString" name="searchString" placeholder="Nhập từ khóa tìm kiếm" class="form-control" style="cursor:pointer" />
        </div>
        <div class="col-md-2">
            <input type="submit" value="Tìm kiếm" class="btn btn-info" />
        </div>
    </div>
}
<div class="col-lg-12 form-group">
    <table class="table table-bordered">
        <tr>
            <th>
                STT
            </th>
            <th>
                Sản Phẩm
            </th>
            <th>
                Đơn Giá
            </th>
            <th>
                Số Lượng
            </th>
            
            <th>
                Danh Mục
            </th>
            <th>Hành Động</th>

        </tr>
        @{ var i = 1;}
        @foreach (var item in Model)
        {
            <tr id="row_@item.ID">
                <td>
                    @i
                </td>
                <td>
                    @item.Name
                </td>
                <td>
                    @string.Format("{0:0,0.}", @item.UnitCost)
                </td>
                <td>
                    @item.Quantity
                </td>
                
                <td>
                    @item.category_name
                </td>
                <td>
                    <a href="@Url.Action("Edit", "Product", new { id = @item.ID })" class="btn btn-primary" style="font-size:12px;"><i class="fa fa-edit"></i></a>
                    <a onclick="PopupDelete(@item.ID)" class="btn btn-danger" style="cursor:pointer; font-size:12px;"><i class="fa fa-trash-o"></i></a>
                    <a href="@Url.Action("Index", "DetailProduct", new { id = @item.ID })" class="btn btn-primary" style="font-size:12px;"><i class="fa fa-eye-slash"></i></a>
                </td>

            </tr>
            i++;
        }

    </table>
</div>
<script>
    function PopupDelete(id) {
        Swal.fire({
            title: 'Bạn có chắc chắn muốn xóa?',
            showCancelButton: true,
            confirmButtonColor: '#56aaff',
            cancelButtonColor: '#ff7f00',
            confirmButtonText: 'Xóa',
            cancelButtonText: 'Bỏ qua',
        }).then((result) => {
            if (result.value) {
                $.ajax({
                    type: "POST",
                    url: "/Product/Delete",
                    data: { id: id },
                    success: function (result) {
                        $("#row_" + id).remove();

                    }
                })

            }
        })
    }
</script>